import React from "react";
import {
  FaTimes,
  FaCalendarAlt,
  FaPlus,
  FaArrowUp,
  FaArrowDown,
  FaArrowRight,
  FaArrowLeft,
  FaArrowsAlt,
  FaChevronLeft,
  FaChevronRight,
  FaCloud,
  FaSearch,
  FaPencilAlt,
  FaEdit,
  FaTags,
  FaList,
  FaCalendarCheck,
  FaCalendarTimes,
  FaStickyNote,
  FaTrash,
  FaCheck,
  FaExpand,
  FaCompress,
  FaShare,
  FaHourglassStart,
  FaHourglassEnd,
  FaFileExport,
  FaBars,
  FaStar,
  FaSquare,
  FaSpinner,
  FaFolder,
  FaCopy,
  FaFile,
  FaCog,
} from "react-icons/fa";
import { property, partialRight } from "lodash/fp";
import { PiPlus, PiColumnsBold, PiRowsBold } from "react-icons/pi";
import { TiTimes } from "react-icons/ti";

const ICONMAPPING = {
  times: <FaTimes />,
  check: <FaCheck />,
  plus: <FaPlus />,
  "arrow-up": <FaArrowUp />,
  "arrow-left": <FaArrowLeft />,
  "arrow-right": <FaArrowRight />,
  "arrow-down": <FaArrowDown />,
  "arrows-alt": <FaArrowsAlt />,
  "chevron-left": <FaChevronLeft />,
  "chevron-right": <FaChevronRight />,
  cloud: <FaCloud />,
  "calendar-alt": <FaCalendarAlt />,
  search: <FaSearch />,
  pencil: <FaPencilAlt />,
  "small-times": <TiTimes />,
  "small-plus": <PiPlus />,
  columns: <PiColumnsBold />,
  rows: <PiRowsBold />,
  edit: <FaEdit />,
  tags: <FaTags />,
  list: <FaList />,
  "calendar-check": <FaCalendarCheck />,
  "calendar-times": <FaCalendarTimes />,
  "sticky-note": <FaStickyNote />,
  trash: <FaTrash />,
  expand: <FaExpand />,
  compress: <FaCompress />,
  share: <FaShare />,
  "hourglass-start": <FaHourglassStart />,
  "hourglass-end": <FaHourglassEnd />,
  "file-export": <FaFileExport />,
  bars: <FaBars />,
  stars: <FaStar />,
  square: <FaSquare />,
  spinner: <FaSpinner />,
  copy: <FaCopy />,
  cogs: <FaCog />,
  folder: <FaFolder />,
  file: <FaFile />,
};

export const getIcon = partialRight(property, [ICONMAPPING]);
